package com.mzs.basket_krk.domain.model

sealed class StatOption(val sign: String)

sealed class NonSummable(sign: String) : StatOption(sign)
sealed class Summable(sign: String) : StatOption(sign)

object StatSeason : NonSummable("S")
object StatTeam : NonSummable("TEAM")
object StatPlayer : NonSummable("PLAYER")
object StatLeague : NonSummable("LGE")
object StatRegularSeason : NonSummable("RS")
object StatPtsPlus : NonSummable("PTS+")
object StatPtsMinus : NonSummable("PTS-")
object StatPtsDiff : NonSummable("DIFF")

object StatMatches : Summable("M")
object StatSeconds : Summable("MIN")
object StatFtm : Summable("FTM")
object StatFta : Summable("FTA")
object StatFtPcg : Summable("FT%")
object StatFgm : Summable("FGM")
object StatFga : Summable("FGA")
object StatFgPcg : Summable("FG%")
object StatFg3m : Summable("3PM")
object StatFg3a : Summable("3PA")
object StatFg3Pcg : Summable("3P%")
object StatPts : Summable("PTS")
object StatAst : Summable("AST")
object StatReb : Summable("REB")
object StatOReb : Summable("ORB")
object StatDReb : Summable("DRB")
object StatStl : Summable("STL")
object StatBlk : Summable("BLK")
object StatTo : Summable("TO")
object StatTech : Summable("TCH")
object StatPFouls : Summable("PF")
object StatPFoulsOn : Summable("FON")
object StatMvp : Summable("MVP")
object StatPlusMinus : Summable("+/-")
object StatEval : Summable("EFF")
